### PR TITLE
overlay: support "userxattr" option (kernel 5.11)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
ref: https://github.com/containerd/containerd/pull/5076

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@ktock Can we have a new release with this?

**Review by ktock — APPROVED** [review]
Thanks for this. 
Yes, let's have the new release today.
We'll need docs for rootless setup for kernel > 5.11 after we have tests.

**Comment by AkihiroSuda** [comment]
Rootless installer and docs are here: https://github.com/containerd/nerdctl/pull/123
This should work with Ubuntu (>= 15.XX? 16.XX?), Debian (>=10), and any distro with kernel >= 5.11.

I also tried to support `fuse-overlayfs` with kernel >= 4.18, but it doesn't seem to be able to update `fetchedPercent` in `/.stargz-snapshotter/*.json` files.

<details>

<p>

```diff
diff --git a/snapshot/snapshot.go b/snapshot/snapshot.go
index 0f5fc96..a174303 100644
--- a/snapshot/snapshot.go
+++ b/snapshot/snapshot.go
@@ -21,6 +21,7 @@ import (
        "fmt"
        "io/ioutil"
        "os"
+       "os/exec"
        "path/filepath"
        "strings"
        "syscall"
@@ -30,9 +31,11 @@ import (
        "github.com/containerd/containerd/mount"
        "github.com/containerd/containerd/snapshots"
        "github.com/containerd/containerd/snapshots/storage"
+       "github.com/containerd/containerd/sys"
        "github.com/containerd/continuity/fs"
        "github.com/moby/sys/mountinfo"
        "github.com/pkg/errors"
+       "github.com/sirupsen/logrus"
        "golang.org/x/sync/errgroup"
 )
 
@@ -51,6 +54,8 @@ const (
        remoteSnapshotLogKey = "remote-snapshot-prepared"
        prepareSucceeded     = "true"
        prepareFailed        = "false"
+
+       fuseOverlayfsBinary = "fuse-overlayfs"
 )
 
 // FileSystem is a backing filesystem abstraction.
@@ -92,6 +97,8 @@ type snapshotter struct {
 
        // fs is a filesystem that this snapshotter recognizes.
        fs FileSystem
+
+       useFuseOverlayfs bool
 }
 
 // NewSnapshotter returns a Snapshotter which can use unpacked remote layers
@@ -113,13 +120,27 @@ func NewSnapshotter(ctx context.Context, root string, targetFs FileSystem, opts
        if err := os.MkdirAll(root, 0700); err != nil {
                return nil, err
        }
-       supportsDType, err := fs.SupportsDType(root)
-       if err != nil {
-               return nil, err
+       var useFuseOverlayfs bool
+       if sys.RunningInUserNS() {
+               // Ubuntu and Debian support rootless overlayfs but unstable, so we do not use.
+               // TODO: support rootless overlayfs (stable) introduced in kernel 5.11
+               logrus.Info("running in user namespace, enabling fuse-overlayfs")
+               useFuseOverlayfs = true
+               if _, err := exec.LookPath(fuseOverlayfsBinary); err != nil {
+                       return nil, err
+               }
        }
-       if !supportsDType {
-               return nil, fmt.Errorf("%s does not support d_type. If the backing filesystem is xfs, please reformat with ftype=1 to enable d_type support", root)
+
+       if !useFuseOverlayfs {
+               supportsDType, err := fs.SupportsDType(root)
+               if err != nil {
+                       return nil, err
+               }
+               if !supportsDType {
+                       return nil, fmt.Errorf("%s does not support d_type. If the backing filesystem is xfs, please reformat with ftype=1 to enable d_type support", root)
+               }
        }
+
        ms, err := storage.NewMetaStore(filepath.Join(root, "metadata.db"))
        if err != nil {
                return nil, err
@@ -130,10 +151,11 @@ func NewSnapshotter(ctx context.Context, root string, targetFs FileSystem, opts
        }
 
        o := &snapshotter{
-               root:        root,
-               ms:          ms,
-               asyncRemove: config.asyncRemove,
-               fs:          targetFs,
+               root:             root,
+               ms:               ms,
+               asyncRemove:      config.asyncRemove,
+               fs:               targetFs,
+               useFuseOverlayfs: useFuseOverlayfs,
        }
 
        if err := o.restoreRemoteSnapshot(ctx); err != nil {
@@ -598,9 +620,13 @@ func (o *snapshotter) mounts(ctx context.Context, s storage.Snapshot, checkKey s
        }
 
        options = append(options, fmt.Sprintf("lowerdir=%s", strings.Join(parentPaths, ":")))
+       mountType := "overlay"
+       if o.useFuseOverlayfs {
+               mountType = "fuse3." + fuseOverlayfsBinary
+       }
        return []mount.Mount{
                {
-                       Type:    "overlay",
+                       Type:    mountType,
                        Source:  "overlay",
                        Options: options,
                },
```

</p>

</details>

**Comment by ktock** [comment]
Thanks. I'll prepare for the new release.

**Pull request merged**
