### PR TITLE
go.mod, Dockerfile: bump up dependencies

### PR DESCRIPTION
**Pull request by ktock**
- go.mod
  - https://github.com/containerd/stargz-snapshotter/pull/1830
  - https://github.com/containerd/stargz-snapshotter/pull/1829
  - https://github.com/containerd/stargz-snapshotter/pull/1828
  - https://github.com/containerd/stargz-snapshotter/pull/1827
  - https://github.com/containerd/stargz-snapshotter/pull/1857
  - https://github.com/containerd/stargz-snapshotter/pull/1856
  - https://github.com/containerd/stargz-snapshotter/pull/1855
  - https://github.com/containerd/stargz-snapshotter/pull/1854
  - https://github.com/containerd/stargz-snapshotter/pull/1853
  - https://github.com/containerd/stargz-snapshotter/pull/1852
  - https://github.com/containerd/stargz-snapshotter/pull/1851
  - https://github.com/containerd/stargz-snapshotter/pull/1850
  - https://github.com/containerd/stargz-snapshotter/pull/1849
  - https://github.com/containerd/stargz-snapshotter/pull/1846
  - https://github.com/containerd/stargz-snapshotter/pull/1845
  - https://github.com/containerd/stargz-snapshotter/pull/1838
  - https://github.com/containerd/stargz-snapshotter/pull/1833
- Dockerfile
  - ~~nerdctl v2.0.0 https://github.com/containerd/nerdctl/releases/tag/v2.0.0~~ see https://github.com/containerd/stargz-snapshotter/pull/1832#issuecomment-2473789391
  - cni plugins: v1.6.0 https://github.com/containernetworking/plugins/releases/tag/v1.6.0
  - runc v1.2.1 https://github.com/opencontainers/runc/releases/tag/v1.2.1
  - podman v5.2.5 https://github.com/containers/podman/releases/tag/v5.2.5
  - cri-o v1.31.2 https://github.com/cri-o/cri-o/releases/tag/v1.31.2
  - common v0.61.0 https://github.com/containers/common/releases/tag/v0.61.0
  - netavark v1.13.0 https://github.com/containers/netavark/releases/tag/v1.13.0

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Can you update this with the latest containerd RC?

**Comment by AkihiroSuda** [comment]
CI is failing
```
79.87 core/sandbox/proxy/controller.go:84:40: undefined: errdefs.FromGRPC
79.87 core/sandbox/proxy/controller.go:106:18: undefined: errdefs.FromGRPC
79.87 core/sandbox/proxy/controller.go:115:18: undefined: errdefs.FromGRPC
79.87 core/sandbox/proxy/controller.go:132:23: undefined: errdefs.FromGRPC
79.87 core/sandbox/proxy/controller.go:158:46: undefined: errdefs.FromGRPC
79.87 core/sandbox/proxy/controller.go:176:23: undefined: errdefs.FromGRPC
79.87 core/sandbox/proxy/controller.go:193:18: undefined: errdefs.FromGRPC
79.87 core/sandbox/proxy/store.go:44:32: undefined: errdefs.FromGRPC
79.87 core/sandbox/proxy/store.go:44:32: too many errors
89.25 make: *** [Makefile:258: bin/ctr] Error 1
```

**Comment by ktock** [comment]
nerdctl v2 now adds port number to the registry host name in config.json, even when user doesn't specify it for nerdctl login. (https://github.com/containerd/nerdctl/blob/ef588dafa080e3dbc9c061ff3802affb66aef291/pkg/imgutil/dockerconfigresolver/registryurl.go#L53).

And that config.json  doesn't seem to work for stargz-snapshotter (and also go-containerregistry (crane)).

For now, let's prioritize cutting a new relese of stargz-snapsshotter because stargz-snapshotter works fine with containerd v2.

**Review by AkihiroSuda — APPROVED** [review]

**Comment by dmcgowan** [comment]
Did one of the deps force the go version in the go.mod to `1.23`?

**Comment by ktock** [comment]
Thanks for the comment. Fixing in  #1863 .

**Pull request merged**
