### PR TITLE
Update rpull.go to fix typos

### PR DESCRIPTION
**Pull request by thundergolfer**

### CODE REVIEW

**Comment by thundergolfer** [comment]
@ktock could a get your eyes on this quick patch 🙏

**Review by ktock — APPROVED** [review]
Thanks

**Comment by thundergolfer** [comment]
@ktock is there something I need to do before this can merge?

**Comment by ktock** [comment]
Sorry for slow reply. Worked on fixing CI issues. Could you rebase this on the latest main to pass CI?

**Comment by thundergolfer** [comment]
Done 👍

**Pull request merged**
