### PR TITLE
Allow some of prioritized files are missed during sort

### PR DESCRIPTION
**Pull request by ktock**
https://github.com/containerd/stargz-snapshotter/pull/212#issuecomment-748483624

This commit adds a new option WithAllowPrioritizeNotFound. This makes Build
continue the execution even if some of prioritized files specified by
WithPrioritizedFiles option aren't found in the input tar. Instead, this records
all missed file names to the passed slice.

### CODE REVIEW

**Comment by ktock** [comment]
@mattmoor  WDYT?

**Comment by mattmoor** [comment]
I see, so this would collect the missed files, so that the caller knows what files were missed?

**Comment by ktock** [comment]
Yes. So caller can optimize the layer in best-effort and know which files are missed.  This information seems needed for indicating some warnings on the caller's side according to https://github.com/google/go-containerregistry/pull/879#issuecomment-748398008 ?

**Comment by mattmoor** [comment]
Yeah I think that'll be perfect for aggregating across layers and images and surfacing back to the user what was missing.

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
